<?php
/**
 * ChannelsRequestData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ShiprocketAPI
 *
 * Welcome to ShipRocket’s API Documentation. Get a clear understanding of all the sections and codes that are used in ShipRocket’s API. ShipRocket API uses the JSON syntax.     First you need to register with ShipRocket and create an account. Simply click on this [link](https://app.shiprocket.in/register) to complete the simple sign up process.    Please note that to utilise the ShipRocket API's, you need to [upgrade](https://app.shiprocket.in/billing-plan-details) your plan to Advance or Pro. To get access to use the API's, you need to call to +91-9266623006 our customer care or send a mail to srs@kartrocket.com, stating that you would like to use ShipRocket Open API's. After that you will have to provide an alternate email id which will be used for the ShipRocket API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ChannelsRequestData Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChannelsRequestData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'channelsRequest_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'name' => 'string',
        'status' => 'string',
        'settings' => '\Swagger\Client\Model\ChannelsRequestSettings',
        'auth' => 'string[]',
        'connections' => 'int',
        'orders_sync' => 'int',
        'inventory_sync' => 'int',
        'orders_synced_on' => 'string',
        'inventory_synced_on' => 'string',
        'base_channel_code' => 'string',
        'base_channel' => '\Swagger\Client\Model\ChannelsRequestBaseChannel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'name' => null,
        'status' => null,
        'settings' => null,
        'auth' => null,
        'connections' => null,
        'orders_sync' => null,
        'inventory_sync' => null,
        'orders_synced_on' => null,
        'inventory_synced_on' => null,
        'base_channel_code' => null,
        'base_channel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'status' => 'status',
        'settings' => 'settings',
        'auth' => 'auth',
        'connections' => 'connections',
        'orders_sync' => 'orders_sync',
        'inventory_sync' => 'inventory_sync',
        'orders_synced_on' => 'orders_synced_on',
        'inventory_synced_on' => 'inventory_synced_on',
        'base_channel_code' => 'base_channel_code',
        'base_channel' => 'base_channel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'status' => 'setStatus',
        'settings' => 'setSettings',
        'auth' => 'setAuth',
        'connections' => 'setConnections',
        'orders_sync' => 'setOrdersSync',
        'inventory_sync' => 'setInventorySync',
        'orders_synced_on' => 'setOrdersSyncedOn',
        'inventory_synced_on' => 'setInventorySyncedOn',
        'base_channel_code' => 'setBaseChannelCode',
        'base_channel' => 'setBaseChannel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'status' => 'getStatus',
        'settings' => 'getSettings',
        'auth' => 'getAuth',
        'connections' => 'getConnections',
        'orders_sync' => 'getOrdersSync',
        'inventory_sync' => 'getInventorySync',
        'orders_synced_on' => 'getOrdersSyncedOn',
        'inventory_synced_on' => 'getInventorySyncedOn',
        'base_channel_code' => 'getBaseChannelCode',
        'base_channel' => 'getBaseChannel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['settings'] = isset($data['settings']) ? $data['settings'] : null;
        $this->container['auth'] = isset($data['auth']) ? $data['auth'] : null;
        $this->container['connections'] = isset($data['connections']) ? $data['connections'] : null;
        $this->container['orders_sync'] = isset($data['orders_sync']) ? $data['orders_sync'] : null;
        $this->container['inventory_sync'] = isset($data['inventory_sync']) ? $data['inventory_sync'] : null;
        $this->container['orders_synced_on'] = isset($data['orders_synced_on']) ? $data['orders_synced_on'] : null;
        $this->container['inventory_synced_on'] = isset($data['inventory_synced_on']) ? $data['inventory_synced_on'] : null;
        $this->container['base_channel_code'] = isset($data['base_channel_code']) ? $data['base_channel_code'] : null;
        $this->container['base_channel'] = isset($data['base_channel']) ? $data['base_channel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The respective channel id’s of the various channels which are to be integrated with the ShipRocket panel.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name 
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status 
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Swagger\Client\Model\ChannelsRequestSettings
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Swagger\Client\Model\ChannelsRequestSettings $settings settings
     *
     * @return $this
     */
    public function setSettings($settings)
    {
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets auth
     *
     * @return string[]
     */
    public function getAuth()
    {
        return $this->container['auth'];
    }

    /**
     * Sets auth
     *
     * @param string[] $auth 
     *
     * @return $this
     */
    public function setAuth($auth)
    {
        $this->container['auth'] = $auth;

        return $this;
    }

    /**
     * Gets connections
     *
     * @return int
     */
    public function getConnections()
    {
        return $this->container['connections'];
    }

    /**
     * Sets connections
     *
     * @param int $connections 
     *
     * @return $this
     */
    public function setConnections($connections)
    {
        $this->container['connections'] = $connections;

        return $this;
    }

    /**
     * Gets orders_sync
     *
     * @return int
     */
    public function getOrdersSync()
    {
        return $this->container['orders_sync'];
    }

    /**
     * Sets orders_sync
     *
     * @param int $orders_sync 
     *
     * @return $this
     */
    public function setOrdersSync($orders_sync)
    {
        $this->container['orders_sync'] = $orders_sync;

        return $this;
    }

    /**
     * Gets inventory_sync
     *
     * @return int
     */
    public function getInventorySync()
    {
        return $this->container['inventory_sync'];
    }

    /**
     * Sets inventory_sync
     *
     * @param int $inventory_sync 
     *
     * @return $this
     */
    public function setInventorySync($inventory_sync)
    {
        $this->container['inventory_sync'] = $inventory_sync;

        return $this;
    }

    /**
     * Gets orders_synced_on
     *
     * @return string
     */
    public function getOrdersSyncedOn()
    {
        return $this->container['orders_synced_on'];
    }

    /**
     * Sets orders_synced_on
     *
     * @param string $orders_synced_on 
     *
     * @return $this
     */
    public function setOrdersSyncedOn($orders_synced_on)
    {
        $this->container['orders_synced_on'] = $orders_synced_on;

        return $this;
    }

    /**
     * Gets inventory_synced_on
     *
     * @return string
     */
    public function getInventorySyncedOn()
    {
        return $this->container['inventory_synced_on'];
    }

    /**
     * Sets inventory_synced_on
     *
     * @param string $inventory_synced_on 
     *
     * @return $this
     */
    public function setInventorySyncedOn($inventory_synced_on)
    {
        $this->container['inventory_synced_on'] = $inventory_synced_on;

        return $this;
    }

    /**
     * Gets base_channel_code
     *
     * @return string
     */
    public function getBaseChannelCode()
    {
        return $this->container['base_channel_code'];
    }

    /**
     * Sets base_channel_code
     *
     * @param string $base_channel_code The two letter code for the respective channels. Please note that the “Manual” channel
     *
     * @return $this
     */
    public function setBaseChannelCode($base_channel_code)
    {
        $this->container['base_channel_code'] = $base_channel_code;

        return $this;
    }

    /**
     * Gets base_channel
     *
     * @return \Swagger\Client\Model\ChannelsRequestBaseChannel
     */
    public function getBaseChannel()
    {
        return $this->container['base_channel'];
    }

    /**
     * Sets base_channel
     *
     * @param \Swagger\Client\Model\ChannelsRequestBaseChannel $base_channel base_channel
     *
     * @return $this
     */
    public function setBaseChannel($base_channel)
    {
        $this->container['base_channel'] = $base_channel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


