<?php
/**
 * ChannelsRequestDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ShiprocketAPI
 *
 * Welcome to ShipRocket’s API Documentation. Get a clear understanding of all the sections and codes that are used in ShipRocket’s API. ShipRocket API uses the JSON syntax.     First you need to register with ShipRocket and create an account. Simply click on this [link](https://app.shiprocket.in/register) to complete the simple sign up process.    Please note that to utilise the ShipRocket API's, you need to [upgrade](https://app.shiprocket.in/billing-plan-details) your plan to Advance or Pro. To get access to use the API's, you need to call to +91-9266623006 our customer care or send a mail to srs@kartrocket.com, stating that you would like to use ShipRocket Open API's. After that you will have to provide an alternate email id which will be used for the ShipRocket API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelsRequestDataTest Class Doc Comment
 *
 * @category    Class */
// * @description ChannelsRequestData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelsRequestDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChannelsRequestData"
     */
    public function testChannelsRequestData()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "settings"
     */
    public function testPropertySettings()
    {
    }

    /**
     * Test attribute "auth"
     */
    public function testPropertyAuth()
    {
    }

    /**
     * Test attribute "connections"
     */
    public function testPropertyConnections()
    {
    }

    /**
     * Test attribute "orders_sync"
     */
    public function testPropertyOrdersSync()
    {
    }

    /**
     * Test attribute "inventory_sync"
     */
    public function testPropertyInventorySync()
    {
    }

    /**
     * Test attribute "orders_synced_on"
     */
    public function testPropertyOrdersSyncedOn()
    {
    }

    /**
     * Test attribute "inventory_synced_on"
     */
    public function testPropertyInventorySyncedOn()
    {
    }

    /**
     * Test attribute "base_channel_code"
     */
    public function testPropertyBaseChannelCode()
    {
    }

    /**
     * Test attribute "base_channel"
     */
    public function testPropertyBaseChannel()
    {
    }
}
